"""add index  to created_at

Revision ID: 8df4979daeed
Revises: c7f71dd6b392
Create Date: 2026-06-07 11:12:32.567641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df4979daeed'
down_revision: Union[str, Sequence[str], None] = 'c7f71dd6b392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_finances_created_at'), 'finances', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finances_created_at'), table_name='finances')
    # ### end Alembic commands ###
